/** Generated File Do not Track.
 * Generated by gen-firment.py based on .proto file.
 * Provides first-level handling of received messages.
 * */
#include <fmt_update.h>
#include <fmt_rx.h>
#include <fmt_comms.h>       // fmt_getMsg()
#include <fmt_log.h>       // fmt_sendLog()
#include <ghostProbe.h>    // handleRunScanCtl()
#include <message_handlers.h> // all project-specific handlers

void fmt_handleRx(void)
{
  Top incomingMessage;
  if (fmt_getMsg(&incomingMessage))
  {
    switch (incomingMessage.which_sub)
    {
    case Top_Ack_tag:
    {
      // New Feature placeholder: handle ack
      break;
    }
      /*--GENERATED CONTENT MARKER--*/
    default:
    }
  }
  else
  { // failed to decode.
    // TODO: figure out why this causes messages to overflow send buffer.
    // fmt_sendLog(LOG_ERROR, "decode error", 0.0F);
  }
}

// Stub handler so consuming project can opt out of building ghostProbe.c
// __attribute__((weak)) void handleRunScanCtl(RunScanCtl msg) {} TODO: fix weak handler for opt-in.

// Stub handler so consuming project can opt out of building fmt_update.c
// __attribute__((weak)) void handleImageData(ImageData msg) {}