/** Generated File Do not Track.
 * Generated by gen-firment.py based on .proto file.
 * Provides first-level handling of received messages.
 * */

#include <fmt_rx.h>
#include <fmt_comms.h>       // fmt_getMsg()
#include <project_msg.pb.h>

/* Include any modules that define messages.
This section requires that the .h file containing message handler functions have
the same name (excluding extension) as the .proto file*/
/*--MODULE INCLUDES GENERATED CONTENT--*/

void fmt_handleRx(void)
{
  Top incomingMessage;
  if (fmt_getMsg(&incomingMessage))
  {
    switch (incomingMessage.which_sub)
    {
      /*--CASE BLOCKS GENERATED CONTENT--*/
    default:
    }
  }
  else
  { // failed to decode.
    // TODO: figure out why this causes messages to overflow send buffer.
    // fmt_sendLog(LOG_ERROR, "decode error", 0.0F);
  }
}

// Stub handler so consuming project can opt out of building ghostProbe.c
// __attribute__((weak)) void handleRunScanCtl(RunScanCtl msg) {} TODO: fix weak handler for opt-in.

// Stub handler so consuming project can opt out of building fmt_update.c
// __attribute__((weak)) void handleImageData(ImageData msg) {}